language: android

android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-m2repository
    - extra-google-m2repository

install:
  - true

sudo: false

script:
  - ./gradlew clean build
